on:
        push:
                branches: [ main ]
jobs:
 test:
  name: Run test
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@master
  - name: Test
    uses: skx/github-action-tester@master
    with:
	script: .github/tests/dontrun-tests.sh
